routes/web.php
<?php

Route::view('/', 'login')->name('login');
Route::get('/logout', 'LoginController@logout');
Route::post('/recuperar-senha', 'LoginController@recuperaSenha');
Route::get('/nova-senha/{token}', 'LoginController@novaSenha');

Route::post('/confirma-nova-senha', 'LoginController@confirmaNovaSenha');

Route::get('/card', function () {
	return Redirect::to('/');
});


Route::get('/meu-ip', function () {
    foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR') as $key){
        if (array_key_exists($key, $_SERVER) === true){
            foreach (explode(',', $_SERVER[$key]) as $ip){
                $ip = trim($ip); // just to be safe
                if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false){
                    dd($ip);
                }
            }
        }
    }
});


Route::prefix('login')->group(function () {
	Route::post('/', 'LoginController@login');
	Route::post('/busca-chave', 'LoginController@buscaChave');
	Route::post('/primeiro-acesso', 'LoginController@primeiroAcesso');
	Route::post('/cadastro', 'LoginController@cadastro');
});


Route::group(['middleware' => ['auth']], function () {

	// Rotas da Loja
	Route::prefix('loja')->group(function () {

		Route::get('/', 'LojaController@index');
		Route::get('/conheca', 'LojaController@conheca');
		Route::get('/contato', 'LojaController@contato');
		Route::post('/contato/enviar', 'LojaController@enviarContato');
		Route::get('/movimentacao', 'LojaController@movimentacao');
		Route::get('/resgates', 'LojaController@resgates');
		Route::get('/perfil', 'LojaController@perfil');
		Route::get('/regulamento', 'LojaController@regulamento');
		Route::get('/termos-condicoes', 'LojaController@termosCondicoes');
		Route::get('/baixar-regulamento/{cod_campanha}/{nome_campanha}', 'LojaController@baixarRegulamentoCampanha');
		Route::get('/notificacoes', 'LojaController@notificacoes');
		Route::get('/videos', 'LojaController@videos');
		Route::post('/videos/marcar-visto', 'StreamingController@marcarVisto');
		Route::get('/lista-desejos', 'LojaController@listaDesejos');
		Route::get('/vouchers-digitais', 'LojaController@vouchers');

		Route::get('/produto/{id}', 'LojaController@produto');

		Route::get('/carrinho', 'CarrinhoController@index');
		Route::post('/adicionar-item-carrinho', 'CarrinhoController@adicionar');
		Route::post('/remover-item-carrinho', 'CarrinhoController@remover');

		Route::post('/edita-perfil', 'LoginController@editaUsuario');
		Route::post('/mudar-senha', 'LoginController@mudarSenha');

		Route::post('/desejados', 'DesejadosController@atualiza');


		Route::post('/resgatar', 'ResgateController@resgatar');
		Route::view('/agradecimentos', 'loja.agradecimentos');

		Route::post('/aplica-cupom', 'CupomController@aplicar');

		Route::post('/salvar-dados', 'LojaController@salvarDados');

		Route::get('/{link}', 'LojaController@categoria'); // Precisa ser a ultima senão outras rotas da loja caem aqui
	});

	// Notification
	Route::prefix('notification')->group(function () {

		Route::get('visualizar/{id}', 'NotificationController@visualiza');

	});


	// Rotas do Super
	Route::prefix('super')->group(function () {
	});

});


// Rotas do sistema
Route::prefix('sistema')->group(function () {

	// Authentication Routes...
	Route::view('/login', 'sistema.login')->name('login-admin');
	Route::post('/efetuar-login', 'AdminLoginController@login');
	Route::post('logout', 'AdminLoginController@logout')->name('logout');

	// Password Reset Routes...
	// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
	// Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

	// Email Verification Routes...
	// Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
	// Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
	// Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');


	// Admin autenticado
	Route::group(['middleware' => ['auth:admin', 'perfil_admin']], function () {

		Route::get('/', function () {
			return Redirect::to('/sistema/campanhas');
		})->name('sistema');

		Route::prefix('helpdesk')->group(function () {
			Route::view('/', 'sistema.helpdesk.helpdesk');
		});



		// Clientes
		Route::prefix('clientes')->group(function () {
			Route::get('/', 'ClienteController@index');

			Route::view('/adicionar', 'sistema.clientes.cadastrar-cliente');

			Route::post('/adicionar-cliente', 'ClienteController@cadastrar');

			Route::get('/{id}/{nome_cliente}', function ($id) {
				return view('sistema.clientes.detalhes-cliente')->with([
					'cliente' => \App\Models\Cliente::withTrashed()->find($id)
				]);
			});

			Route::get('/editar/{id}/{nome_cliente}', function ($id) {
				return view('sistema.clientes.editar-cliente')->with([
					'cliente' => \App\Models\Cliente::withTrashed()->find($id)
				]);
			});

			Route::post('/editar-cliente', 'ClienteController@editar');

			Route::post('/excluir-cliente', 'ClienteController@excluir');

			Route::post('/ativar-cliente', 'ClienteController@ativar');

			Route::post('/filtrar', 'ClienteController@filtrar');

			Route::post('/listar-campanhas', 'ClienteController@listarCampanhas');

			Route::post('/listar-pdvs', 'ClienteController@listarPdvs');


			Route::get('/{id}/{nome_cliente}/pdv/adicionar', function ($id) {
				return view('sistema.pdvs.cadastrar-pdv')->with([
					'cliente' => \App\Models\Cliente::find($id)
				]);
			});

			Route::post('/pdv/adicionar-pdv', 'PdvController@cadastrar');

			Route::get('/{id_cliente}/{nome_cliente}/pdv/{id_pdv}/{nome_pdv}/editar', function ($id_cliente, $nome_cliente, $id_pdv) {
				return view('sistema.pdvs.editar-pdv')->with([
					'pdv' => \App\Models\ClientePdv::find($id_pdv)
				]);
			});

			Route::post('/pdv/editar-pdv', 'PdvController@editar');

			Route::post('/pdv/excluir-pdv', 'PdvController@excluir');

			Route::post('/pdv/ativar-pdv', 'PdvController@ativar');

		});


		// Campanhas
		Route::prefix('campanhas')->group(function () {
			Route::get('/', 'CampanhaController@index');

			Route::get('/adicionar', function () {
				return view('sistema.campanhas.cadastrar-campanha')->with([
					'clientes' => \App\Models\Cliente::all()
				]);
			});

			Route::post('/adicionar-campanha', 'CampanhaController@cadastrar');

			Route::get('/{id}/{titulo_campanha}', function ($id) {
				return view('sistema.campanhas.detalhes-campanha')->with([
					'campanha' => \App\Models\Campanha::withTrashed()->find($id),
					'categorias' => \App\Models\CategoriaProduto::with(['produtos' => function ($q) {
						$q->where('disponibilidade', [1, 3]);
					}])->orderBy('categoria', 'ASC')->get()
				]);
			});

			Route::get('/editar/{id}/{nome_campanha}', function ($id) {
				return view('sistema.campanhas.editar-campanha')->with([
					'campanha' => \App\Models\Campanha::withTrashed()->find($id)
				]);
			});

			Route::post('/filtrar', 'CampanhaController@filtrar');

			Route::post('/filtrar-usuarios-campanha', 'CampanhaController@filtrarUsuarios');

			Route::post('/filtrar-resgates-campanha', 'CampanhaController@filtrarResgates');

			Route::post('/listar-ilhas', 'CampanhaController@listarIlhas');

			Route::post('/listar-pdvs', 'ClienteController@listarPdvs');

			Route::post('/pdvs', 'CampanhaController@pdvs');

			Route::post('/editar-campanha', 'CampanhaController@editar');

			Route::post('/excluir-campanha', 'CampanhaController@excluir');

			Route::post('/ativar-campanha', 'CampanhaController@ativar');

			// Carga de pontos normal
			Route::post('/adicionar-carga-de-pontos', 'CargaDePontosController@recebeCarga');
			Route::post('/salvar-carga-de-pontos', 'CargaDePontosController@salvarCarga');
			Route::post('/excluir-carga-de-pontos', 'CargaDePontosController@excluirCarga');
			Route::post('/efetivar-carga-de-pontos', 'CargaDePontosController@efetivarCarga');
			Route::get('/download-carga-de-pontos/{arquivo}/{nome}', 'CargaDePontosController@downloadCarga');
			Route::get('/{id_campanha}/{titulo_campanha}/protocolo/{id_protocolo}', function ($id_campanha, $titulo_campanha, $id_protocolo) {
				$protocolo = \App\Models\CampanhaProtocolo::find($id_protocolo);
				return view('sistema.cargas.carga')->with([
					'campanha' => \App\Models\Campanha::find($id_campanha),
					'nome_arquivo' => $protocolo->arquivo,
					'estatistica' => json_decode($protocolo->dados)->estatistica,
					'usuarios' => json_decode($protocolo->dados)->arrUsuarios,
					'protocolo' => $protocolo
				]);
			});
			Route::get('/{id}/{titulo_campanha}/carga-de-pontos', function ($id) {
				return view('sistema.cargas.carga')->with('campanha', \App\Models\Campanha::find($id));
			})->name('carga-de-pontos');

			// Carga de pontos temporária
			Route::post('/adicionar-carga-de-pontos-temporaria', 'CargaDePontosTemporariosController@recebeCarga');
			Route::post('/salvar-carga-de-pontos-temporaria', 'CargaDePontosTemporariosController@salvarCarga');
			Route::post('/excluir-carga-de-pontos-temporaria', 'CargaDePontosTemporariosController@excluirCarga');
			Route::post('/efetivar-carga-de-pontos-temporaria', 'CargaDePontosTemporariosController@efetivarCarga');
			Route::get('/download-carga-de-pontos-temporaria/{arquivo}/{nome}', 'CargaDePontosTemporariosController@downloadCarga');
			Route::get('/{id_campanha}/{titulo_campanha}/protocolo-temporario/{id_protocolo}', function ($id_campanha, $titulo_campanha, $id_protocolo) {

app/Models/Resgate.php
<?php

/**
 * Created by Reliese Model.
 * Date: Mon, 17 Jun 2019 14:33:20 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Resgate
 *
 * @property int $cod_resgate
 * @property int $cod_usuario
 * @property int $cod_carrinho
 * @property int $cod_entrega
 * @property int $cod_status
 * @property string $registro
 * @property float $valor_resgate
 * @property float $valor_pontos
 * @property \Carbon\Carbon $data_entregue
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @property \App\Models\Carrinho $carrinho
 * @property \App\Models\StatusResgate $status_resgate
 * @property \App\Models\User $user
 *
 * @package App\Models
 */
class Resgate extends Eloquent
{
	protected $table = 'resgate';
	protected $primaryKey = 'cod_resgate';

	protected $casts = [
		'cod_usuario' => 'int',
		'cod_carrinho' => 'int',
		'cod_entrega' => 'int',
		'cod_status' => 'int',
		'valor_resgate' => 'float',
        'valor_pontos' => 'float'
	];

	protected $dates = [
		'data_entregue'
	];

	protected $fillable = [
		'cod_usuario',
		'cod_carrinho',
		'cod_entrega',
		'cod_campanha',
		'cod_status',
		'registro',
		'valor_resgate',
		'data_entregue',
        'valor_pontos'
	];

	protected $appends = ['mes'];

	public function carrinho()
	{
		return $this->belongsTo(\App\Models\Carrinho::class, 'cod_carrinho');
	}

	public function status_carrinho()
	{
		return $this->belongsTo(\App\Models\StatusResgate::class, 'cod_status');
	}

	public function campanha()
	{
		return $this->belongsTo(\App\Models\Campanha::class, 'cod_campanha')->withTrashed();
	}

	public function user()
	{
		return $this->belongsTo(\App\Models\User::class, 'cod_usuario')->withTrashed();
	}

	public function getValorFAttribute(){

		return number_format($this->attributes['valor_resgate'], 0, ',', '.');
	}

	public function getMesAttribute(){
		return $this->created_at->format('M/Y');
	}

	public function getDataResgateAttribute(){
		return $this->created_at->format('d/M/Y . H:i:s');
	}

	public function getPrevisaoEntregaAttribute(){
		return $this->created_at->addDays(35)->format('d/M/Y');
	}




}

app/Models/Video.php
<?php

/**
 * Created by Reliese Model.
 * Date: Tue, 24 Sep 2019 15:23:22 -0300.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;
use Storage;

/**
 * Class Video
 *
 * @property int $cod_video
 * @property int $cod_campanha
 * @property string $titulo
 * @property string $descricao
 * @property string $foto_capa
 * @property string $link_video
 * @property string $extensao
 * @property \Carbon\Carbon $data_entrada
 * @property \Carbon\Carbon $data_saida
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property int $cod_cliente
 * @property int $tipo_streaming
 * @property string $deleted_at
 *
 * @property \App\Models\Campanha $campanha
 * @property \App\Models\Cliente $cliente
 * @property \Illuminate\Database\Eloquent\Collection $usuario_videos
 * @property \Illuminate\Database\Eloquent\Collection $video_origems
 * @property \Illuminate\Database\Eloquent\Collection $vinculos
 *
 * @package App\Models
 */
class Video extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;
	protected $table = 'video';
	protected $primaryKey = 'cod_video';

	const STREAMING_GERAL    = 1;
	const STREAMING_CLIENTE  = 2;
	const STREAMING_CAMPANHA = 3;
	const STREAMING_ILHA     = 4;

	protected $casts = [
		'cod_campanha' => 'int',
		'cod_cliente' => 'int',
		'tipo_streaming' => 'int'
	];

	protected $dates = [
		'data_entrada',
		'data_saida'
	];

	protected $fillable = [
		'cod_campanha',
		'titulo',
		'descricao',
		'foto_capa',
		'link_video',
		'extensao',
		'data_entrada',
		'data_saida',
		'cod_cliente',
		'tipo_streaming'
	];

	public function campanha()
	{
		return $this->belongsTo(\App\Models\Campanha::class, 'cod_campanha');
	}

	public function cliente()
	{
		return $this->belongsTo(\App\Models\Cliente::class, 'cod_cliente');
	}

	public function usuario_videos()
	{
		return $this->hasMany(\App\Models\UsuarioVideo::class);
	}

	public function origem()
	{
		return $this->hasMany(\App\Models\VideoOrigem::class, 'cod_video');
	}

	public function vinculo()
	{
		return $this->hasMany(\App\Models\Vinculo::class, 'cod_video');
	}

    public function getTipoAttribute()
    {
        switch ($this->extensao):
            case 'mp3':
                return 'audio';
                break;
            case 'mp4':
                return 'video';
                break;

        endswitch;
    }


    public function getLinkAttribute()
    {
        switch ($this->extensao):
            case 'mp3':
                return Storage::disk('s3')->url('audio/' . $this->link_video);
                break;
            case 'mp4':
                return Storage::disk('s3')->url('videos/' . $this->link_video);
                break;

        endswitch;
    }

    public function getFotoCapaAttribute()
    {

        return Storage::disk('s3')->url('video-capa/' . $this->attributes['foto_capa']);
    }
}

resources/views/sistema/resgates/lista-resgates.blade.php
@foreach ($resgates as $item)
        <div class="item-table item-resgate">
            <ul class="dados">
                <li>
                    <div class="check-square" data-cod_resgate={{ $item->cod_item }}></div>
                </li>
                <li>
                    <span>{{ preg_replace("/_/", " ", $item->carrinho->resgates->first()->user->nome_usuario) }}</span>
                </li>
                <li>
                    <span>{{ $item->carrinho->resgates->first()->user->login }}</span>
                </li>
                <li>
                    <span>{{ $item->carrinho->resgates->first()->data_resgate }}</span>
                </li>
                <li>
                    <span>{{ $item->produto->nome_produto }} - R${{ $item->produto->valor_reais }}</span>
                </li>
                <li>
                    <span>{{ $item->carrinho->resgates->first()->campanha->nome_campanha }}</span>
                </li>
                <li>
                    <span>{{ $item->carrinho->resgates->first()->user->pdv->nome_pdv }}</span>
                </li>
                <li>
                    <span>{{ $item->status_resgate->descricao_status }}</span>
                </li>
                <li>
                    <div class="pts">
                        <i class="icone-circulo-estrela"></i>
                        <i class="seta icone-arrow-right"></i>
                        <span>{{ $item->produto->valor_produto }}</span>
                    </div>
                </li>
                <i class="icone-arrow-down"></i>
            </ul>
            <div class="dados-gerais">
                <div class="item-dados">
                    <div class="title">
                        <i class="icone-user"></i>
                        <span>inf. do usuários</span>
                    </div>
                    <ul>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->nome_usuario }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->celular }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->email }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>Login - {{ $item->carrinho->resgates->first()->user->login }}</span>
                        </li>
                    </ul>
                </div>
                <div class="item-dados">
                    <div class="title">
                        <i class="icone-user"></i>
                        <span>inf. da entrega</span>
                    </div>
                    <ul>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>CEP - {{ $item->carrinho->resgates->first()->user->pdv->cep }} / {{ $item->carrinho->resgates->first()->user->pdv->estado }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->pdv->cidade }} - {{ $item->carrinho->resgates->first()->user->pdv->estado }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->pdv->bairro }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->carrinho->resgates->first()->user->pdv->logradouro }},
                                {{ $item->carrinho->resgates->first()->user->pdv->numero }}{{ ' ('. $item->carrinho->resgates->first()->user->pdv->complemento . ')' }}</span>
                        </li>
                    </ul>
                </div>
                <div class="item-dados">
                    <div class="title">
                        <i class="icone-resgate"></i>
                        <span>INF. D0 RESGATE</span>
                    </div>
                    <ul>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->produto->nome_produto }} - R${{ $item->produto->valor_reais }}</span>
                        </li>
                        <li>
                            <i class="icone-arrow-right"></i>
                            <span>{{ $item->produto->produto_tipo->nome_tipo }}</span>
                        </li>
{{--                        @if ($item->produto->tipo == 2)--}}
{{--                        <li>--}}
{{--                            <i class="icone-arrow-right"></i>--}}
{{--                            <a href="#"><span>(Enviar voucher)</span></a>--}}
{{--                        </li>--}}
{{--                        @endif--}}
                    </ul>
                </div>
                <div class="item-dados">
                    <div class="title">
                        <i class="icone-cartao"></i>
                        <span>STATUS DA ENTREGA</span>
                    </div>
                    <div class="form-group">
                        <div class="select-custom" cod-item='{{ $item->cod_item }}' >
                            <a href="" class="item-selected">
                                <span>{{ $item->status_resgate->descricao_status }}</span>
                            </a>
                            <div class="dropdown">
                                <ul>
                                    @foreach (\App\Models\StatusResgate::all() as $s)
                                        <li><a href="" class="option-status" cod-opcao="{{ $s->cod_status }}">{{ $s->descricao_status }}</a></li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endforeach

resources/views/sistema/resgates/resgates.blade.php
@extends('sistema.layout.admin-layout')

@section('titulo', 'Resgates')

@section('conteudo')

<main>
      @include('sistema.includes.menu-admin')

      <section class="s-resgates">
            <div class="sidebar-resgate">
                  <form id="form-filtro-resgates">
                        <div class="cont" id="form-pesquisa-inicial">
                              <div class="titulo">
                                    <h1><i class="icone-arrow-right"></i> resgates</h1>
                                    <a style="cursor: pointer" onclick="filtroResgates.exportar()">
                                          <img src="{{ asset("img/icons-adm/icone-exportar.svg") }}" alt="">
                                    </a>
                              </div>
                              <div class="form-group">
                                    <input type="text" id="pesquisa-resgates" name='pesquisa'>
                                    <img src="{{ asset("img/icons-adm/lupa-roxa.svg") }}" alt="">
                              </div>
                              <div class="form-group">
                                    <label for="">Data Inicial</label>
                                    <input type="text" mask="date" name="data_inicial" value="{{ date('d/m/Y', strtotime(\Carbon\Carbon::now()->subMonth())) }}">
                              </div>
                              <div class="form-group">
                                    <label for="">Data Final</label>
                                    <input type="text" mask="date" name="data_final" value="{{ date('d/m/Y', strtotime(\Carbon\Carbon::now())) }}">
                              </div>
                              <div class="form-group">
                                  <label for="">Tipo de Produto</label>
                                  <div class="select-custom">
                                      <input type="hidden" name="tipo_produto" id="pesquisa-tipo-produto">
                                      <a href="" class="item-selected">
                                          <span>Selecione</span>
                                      </a>
                                      <div class="dropdown">
                                          <ul>
                                              <li><a href="" class="resgates-option-cliente" cod-opcao="">Todos</a></li>
                                              @foreach(\App\Models\ProdutoTipo::all() as $tipo)
                                                <li><a href="" class="resgates-option-cliente" cod-opcao="{{ $tipo->cod_tipo }}">{{ $tipo->nome_tipo }}</a></li>
                                              @endforeach
                                          </ul>
                                      </div>
                                  </div>
                              </div>
                              <div class="form-group" style="display: block;">
                                    <label for="">Status da Entrega </label>
                                    <div class="todos-pdvs" id="todosStatus">
                                          @foreach (\App\Models\StatusResgate::orderBy('descricao_status', 'ASC')->get() as $s)
                                                <div class="check {{ $s->cod_status != 4 ? 'checked' : '' }}" data-cod="{{ $s->cod_status }}">
                                                      <div class="square"></div>
                                                      <span>{{ $s->descricao_status }}</span>
                                                </div>
                                          @endforeach
                                    </div>
                              </div>

                              <div class="form-group">
                                    <label for="">Cliente</label>
                                    <div class="select-custom">
                                          <input type="hidden" name="cod_cliente">
                                          <a href="" class="item-selected">
                                                <span>Selecione</span>
                                          </a>
                                          <div class="dropdown">
                                                <ul>
                                                    <li>
                                                        <a href="" class="resgates-option-cliente" cod-opcao="">Todos</a>
                                                    </li>
                                                      @foreach (\App\Models\Cliente::all() as $c)
                                                      <li>
                                                            <a href="" class="resgates-option-cliente"
                                                                  cod-opcao="{{ $c->id }}">
                                                                  {{ $c->nome_fantasia }}
                                                            </a>
                                                      </li>
                                                      @endforeach
                                                </ul>
                                          </div>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label for="">Campanha</label>
                                    <div class="select-custom" id="select-campanha">
                                          <input type="hidden" id="hidden-cod-campanha" name="cod_campanha">
                                          <a href="" class="item-selected">
                                                <span>Selecione</span>
                                          </a>
                                          <div class="dropdown">
                                                <ul id="campanhas-cliente">
                                                </ul>
                                          </div>
                                    </div>
                              </div>
                              <div class="form-group" id="todos-pdvs">
                                    <label for="">PDVS</label>
                                    <div class="todos-pdvs" id='todosPdvs'>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <button type="button" id="btn-filtrar-resgates">filtrar<i class="icone-arrow-right"></i></button>
                              </div>
                        </div>
                        <div class="cont" id="status-lote">
                              <div class="titulo">
                                    <h1><i class="icone-arrow-right"></i> resgates</h1>
                              </div>
                              <h4><span>00</span> linha(s) selecionada(s) </h4>
                              <div class="form-group">
                                    <label for="">Status da Entrega</label>
                                    <div class="select-custom">
                                          <input type="hidden" name="cod_status">
                                          <a href="" class="item-selected">
                                                <span>Selecione</span>
                                          </a>
                                          <div class="dropdown">
                                                <ul>
                                                      @foreach (\App\Models\StatusResgate::orderBy('descricao_status', 'ASC')->get() as $s)
                                                      <li>
                                                            <a href="" cod-opcao="{{ $s->cod_status }}">{{ $s->descricao_status }}</a>
                                                      </li>
                                                      @endforeach
                                                </ul>
                                          </div>
                                    </div>
                              </div>
                              <a style="cursor: pointer" onclick="filtroResgates.exportar()">
                                    <img src="{{ asset("img/icons-adm/icone-exportar.svg") }}" alt="">
                              </a>
                        </div>
                  </form>
            </div>
            <div class="tabela-dados-resgate" id="tabela-resgate">
                    <div class="loader">
                        <i class="fa fa-spinner fa-spin"></i>
                    </div>
                  <ul class="head">
                        <li>
                              <div class="check-square check-all"></div>
                        </li>
                        <li>
                              <span>nome</span>
                        </li>
                        <li>
                              <span>re</span>
                        </li>
                        <li>
                              <span>data-hora</span>
                        </li>
                        <li>
                              <span>Cartão</span>
                        </li>
                        <li>
                              <span>campanha</span>
                        </li>
                        <li>
                              <span>pdv</span>
                        </li>
                        <li>
                              <span>status</span>
                        </li>
                        <li>
                              <span>pontos</span>
                        </li>
                  </ul>
                  <div class="body" id='linhas-resgates'>

                  </div>
            </div>
      </section>

</main>

@stop



@section('onload')
<script>
$(document).ready(function() {
    filtroResgates.filtrar();

    $(document).on("click", "#todosStatus .check", function() {
        $(this).toggleClass("checked");
    });
})
</script>
@stop